# Generated by Django 4.1.3 on 2022-12-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0002_material_productmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productMaterial',
            field=models.ManyToManyField(through='simpleapp.ProductMaterial', to='simpleapp.material'),
        ),
    ]
